var GAME_LEVELS = [
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                                     x                     ",
   "                                                                                                                     x                     ",
   "                                                                                                                     x                     ",
   "                                                                                                                     x                     ",
   "                                                                                                                     x                     ",
   "                                                                                                                     x                     ",
   "                                                                                                                     x                     ",
   "                                                                                        !!!!!!!!                     x                     ",
   "                                                                                       !!                            x                     ",
   " o                                                                                !!!!!!!!                           x                     ",
   "                                                                                 !!                                  x                     ",
   "                                                                                 !!               !!xxxxxx           x                     ",
   "                                                                                 !!               !!x             z  x                     ",
   "                                                                                 !!         xxxxx !!x                x                     ",
   "xxx                                                                              !!               !!x                x                     ",
   "xxx                                                                              !!                 x          xxxxxxx                     ",
   "xxx                                                           xxxxx              !!                 x                x                     ",
   "xxx                                             xxxxx                            !!                 x             z  x                     ",
   "xxx                                                                              !!                 x                x                     ",
   "xxx                                   xxxxx                                                         x    z           x                     ",
   "xxx    @                              xxxxx                                                         x                x                     ",
   "xxx                                   xxxxx                               xxxxx                     x xxxx           x                     ",
   "xxx               xxxxx               xxxxx                                x                         z  x                                  ",
   "xx            o   xxxxx               xxxxx                                                                                                ",
   "xx                xxxxx               xxxxx                                                                                                ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                          o                                                     ",
   "   x           z                   x                                                 x                                                     ",
   "                                                                                     x                                                     ",
   "                                                  z                          z       x                                                     ",
   "                                                                                                                                           ",
   "                                                                                                         ?????????                         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                 x!x                       x!!x                       xxxxxxx                                   x!x  ",
   "                 x!x                       x!!x                    xxxx     xxxxxxxxxxxxxxxxxx                  x!x  ",
   "                 x!x                       x!!xxxxxxxxxxxxxxxxxxxxxx           xx            xx                 x!x  ",
   "                 x!x                 !!!!!!x                     xx             xx            xx                     ",
   "                 xvx                 !xxxxxx                     x               x             x                  x!x",
   "                                     !     x                     x                             x                 xx!x",
   "                                     !     x                                                   x   xxxxxxxxxxxxxxx!!x",
   "                                     !     x                           x   x                   x!!!!!!!!!!!!!!!!!xxx ",
   "                                     !     x            xxxxxxxxxxxx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx ",
   "                                     !     x            x         xx!!!!!!!!!!!xx              x                     ",
   "                                     !     x            x         xxxx!!!!v!xxx               xx                     ",
   "                xx xx           x   x!     xxx  z       x           xxxxxx xx       xxxx       xxxx                  ",
   "              xx     xx         x   x!       x          x                           x x!!!!!!!!xxxx                  ",
   "             xx!!!!!!!xx        x   x!       xx         x                             x!!!!!!!!x                     ",
   "             x!!!!!!!!!x        x   x!       x          x                             xx!!!!!!!x                     ",
   "             x!!!!!!!!!x        x   x!       x          x                             x!!!!!!!!x                     ",
   "             x!!!!!!!!!x        x   x!       x          x               x   x         x!!!!!!!!!x                    ",
   "             x!!!!!!!!!x        x   x!       x     z    x               x   x         x!!!!!!!!!x                   o",
   "             x!!!!!!!!!x        x   x!       x          x     xxxxxx    x!!!x   xxxxxxxxx!!!!!!!x                    ",
   "             x!!!!!!!!!x        x o x!       x         xx               x!!!x   x               x                    ",
   "     @       x!!!!!!!!!x        x   x!       x          x               x!!!x   x               x                    ",
   "    xxx      x!!!!!!!!!x        x   x!       x          x               x!!!xxxxxxx xxxxxx      x                    ",
   "    x x      x!!!!!!!!!x       xx o xx      x           x           xxxxx!!!!!!!!!x          xxxx                    ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!xx     xx    xx        xxxxxxxxxx     x!!!!!!!!!!!!x x         x                       ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!xx       xxxxxxx        x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                       ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!x    o                  x!!!!!!xx !                    xx     xx                        ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!x                       x!!!!!!xx !                     xxxxxxx                         ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!xx       xxxxxxxxxxx!!!!!!!!!xx   !                                                     ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !$$$$$$$                                              ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !xxxxxxx                                              "],
  ["o                                                                                                             ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xxxx                                                                                                        ",
   "  xxxx                                                                                                        ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                  oooo  oooo   oooo   ooo   oooo ooooo  o                                                  ",
   "  x                  o     o      o      o  o  o      o    o                                                  ",
   "  x                  oooo  oooo   o      ooo   oooo   o    o                         ????????????             ",
   "  x                     o  o      o      o  o  o      o                             xxxxxxxxxxxxxx            ",
   "  x                  oooo  oooo   oooo   o  o  oooo   o    o                       xxxxxxxxxxxxxxxx           ",
   "  x       @                                                                       xxxxxxxxxxxxxxxxxx          ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
